name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - windows/amd64
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Go Build
        uses: zijiren233/go-build-action@v1
        env:
          MICRO_ARM64_DISABLED: true
        with:
          targets: ${{ matrix.targets }}
          disable-cgo: true
          enable-micro: true
          result-dir: ./dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          append_body: false
          fail_on_unmatched_files: true
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Dev Build' }}
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'dev' }}
          files: |
            dist/*
